branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # This is for when a pull request is opened.
    - master

env:
  global:
    - PACKAGE="Rust Enhanced"
    - SUBLIME_TEXT_VERSION="3"

language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly

before_install:
  - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh

  # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
    fi


install:
  # Install Sublime and Sublime Unittesting.
  - sh travis.sh bootstrap
  # Install Package Control, needed for dependencies.
  - sh travis.sh install_package_control

  # Ensure nightly is installed to run benchmarks and Clippy.
  # Pin a known good version of nightly and clippy.
  - >
    if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
      rustup install nightly-2018-08-04;
      host=$(rustc -Vv | grep ^host: | sed -e "s/host: //g");
      toolchains=$(dirname $(dirname $(dirname $(rustup which rustc))));
      mv $toolchains/nightly-* $toolchains/nightly-$host;
    fi
  # Install Rust packages needed by integration tests.
  - rustup component add clippy-preview --toolchain=nightly
  - cargo install cargo-script


script:
  - sh travis.sh run_syntax_tests
  - sh travis.sh run_tests
